<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Traits\BelongsToTenant;

// total is a PostgreSQL GENERATED column (amount + tax) — never set it in PHP.
class Invoice extends Model
{
    use HasFactory, HasUuids, SoftDeletes, BelongsToTenant;

    protected $fillable = [
        'tenant_id',
        'contract_id',
        'milestone_id',
        'invoice_number',
        'issue_date',
        'due_date',
        'amount',
        'tax',
        // 'total' is GENERATED by PostgreSQL — excluded from $fillable
        'status',
        'paid_at',
        'notes',
    ];

    protected $casts = [
        'id'         => 'string',
        'issue_date' => 'date',
        'due_date'   => 'date',
        'amount'     => 'float',
        'tax'        => 'float',
        'total'      => 'float',
        'paid_at'    => 'datetime',
        'deleted_at' => 'datetime',
    ];

    public function contract()
    {
        return $this->belongsTo(Contract::class);
    }

    public function milestone()
    {
        return $this->belongsTo(Milestone::class);
    }
}
